services:
    postgresql-master:
        image: bitnami/postgresql:latest
        restart: unless-stopped
        ports:
            - '2345:5432/tcp'
        volumes:
            - pg-master-data:/bitnami/postgresql
        environment:
            - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
            - POSTGRESQL_LOG_HOSTNAME=true
            - POSTGRESQL_REPLICATION_MODE=master
            - POSTGRESQL_REPLICATION_USER=repl_user
            - POSTGRESQL_REPLICATION_PASSWORD=repl_user
            - POSTGRESQL_USERNAME=postgres
            - POSTGRESQL_PASSWORD=<YOUR_PASSWORD>
            - POSTGRESQL_DATABASE=api_gateway
    redis-master:
        image: bitnami/redis:latest
        restart: unless-stopped
        ports:
            - '9736:6379/tcp'
        environment:
            - REDIS_PASSWORD=<YOUR_PASSWORD>

volumes:
    pg-master-data:
        name: pg-master-data